//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magensa.MPPGv3.ServiceClient
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessCardSwipeRequest", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessCardSwipeRequest : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private Magensa.MPPGv3.ServiceClient.Authentication AuthenticationField;
        
        private Magensa.MPPGv3.ServiceClient.CardSwipeInput CardSwipeInputField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.CardSwipeInput CardSwipeInput
        {
            get
            {
                return this.CardSwipeInputField;
            }
            set
            {
                this.CardSwipeInputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInput
        {
            get
            {
                return this.TransactionInputField;
            }
            set
            {
                this.TransactionInputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authentication", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class Authentication : object
    {
        
        private string CustomerCodeField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardSwipeInput", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class CardSwipeInput : object
    {
        
        private string CVVField;
        
        private Magensa.MPPGv3.ServiceClient.EncryptedCardSwipe EncryptedCardSwipeField;
        
        private string ZIPField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVV
        {
            get
            {
                return this.CVVField;
            }
            set
            {
                this.CVVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.EncryptedCardSwipe EncryptedCardSwipe
        {
            get
            {
                return this.EncryptedCardSwipeField;
            }
            set
            {
                this.EncryptedCardSwipeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZIP
        {
            get
            {
                return this.ZIPField;
            }
            set
            {
                this.ZIPField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionInput", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Magensa.MPPGv3.ServiceClient.ReferenceIDTransactionInput))]
    public partial class TransactionInput : object
    {
        
        private System.Nullable<decimal> AmountField;
        
        private string ProcessorNameField;
        
        private System.Collections.Generic.KeyValuePair<string, string>[] TransactionInputDetailsField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionType TransactionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ProcessorName
        {
            get
            {
                return this.ProcessorNameField;
            }
            set
            {
                this.ProcessorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] TransactionInputDetails
        {
            get
            {
                return this.TransactionInputDetailsField;
            }
            set
            {
                this.TransactionInputDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.TransactionType TransactionType
        {
            get
            {
                return this.TransactionTypeField;
            }
            set
            {
                this.TransactionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncryptedCardSwipe", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class EncryptedCardSwipe : object
    {
        
        private string DeviceSNField;
        
        private string KSNField;
        
        private string MagnePrintField;
        
        private string MagnePrintStatusField;
        
        private string Track1Field;
        
        private string Track2Field;
        
        private string Track3Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceSN
        {
            get
            {
                return this.DeviceSNField;
            }
            set
            {
                this.DeviceSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MagnePrint
        {
            get
            {
                return this.MagnePrintField;
            }
            set
            {
                this.MagnePrintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MagnePrintStatus
        {
            get
            {
                return this.MagnePrintStatusField;
            }
            set
            {
                this.MagnePrintStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track1
        {
            get
            {
                return this.Track1Field;
            }
            set
            {
                this.Track1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Track2
        {
            get
            {
                return this.Track2Field;
            }
            set
            {
                this.Track2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track3
        {
            get
            {
                return this.Track3Field;
            }
            set
            {
                this.Track3Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceIDTransactionInput", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ReferenceIDTransactionInput : Magensa.MPPGv3.ServiceClient.TransactionInput
    {
        
        private string ReferenceAuthCodeField;
        
        private string ReferenceTransactionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceAuthCode
        {
            get
            {
                return this.ReferenceAuthCodeField;
            }
            set
            {
                this.ReferenceAuthCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ReferenceTransactionID
        {
            get
            {
                return this.ReferenceTransactionIDField;
            }
            set
            {
                this.ReferenceTransactionIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionType", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public enum TransactionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SALE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AUTHORIZE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CAPTURE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VOID = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REFUND = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FORCE = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REJECT = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TOKEN = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORT = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessCardSwipeResponse", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessCardSwipeResponse : object
    {
        
        private Magensa.MPPGv3.ServiceClient.CardSwipeOutput CardSwipeOutputField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFaultField;
        
        private string MagTranIDField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutputField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.CardSwipeOutput CardSwipeOutput
        {
            get
            {
                return this.CardSwipeOutputField;
            }
            set
            {
                this.CardSwipeOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFault
        {
            get
            {
                return this.MPPGv3WSFaultField;
            }
            set
            {
                this.MPPGv3WSFaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutput
        {
            get
            {
                return this.TransactionOutputField;
            }
            set
            {
                this.TransactionOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardSwipeOutput", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class CardSwipeOutput : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private string CardIDField;
        
        private System.Nullable<bool> IsReplayField;
        
        private System.Nullable<decimal> MagnePrintScoreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardID
        {
            get
            {
                return this.CardIDField;
            }
            set
            {
                this.CardIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsReplay
        {
            get
            {
                return this.IsReplayField;
            }
            set
            {
                this.IsReplayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MagnePrintScore
        {
            get
            {
                return this.MagnePrintScoreField;
            }
            set
            {
                this.MagnePrintScoreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MPPGv3WSFault", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class MPPGv3WSFault : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalFaultDataField;
        
        private string CustomerTransactionIDField;
        
        private string FaultCodeField;
        
        private string FaultReasonField;
        
        private string MagTranIDField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalFaultData
        {
            get
            {
                return this.AdditionalFaultDataField;
            }
            set
            {
                this.AdditionalFaultDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultCode
        {
            get
            {
                return this.FaultCodeField;
            }
            set
            {
                this.FaultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultReason
        {
            get
            {
                return this.FaultReasonField;
            }
            set
            {
                this.FaultReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionOutput", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class TransactionOutput : object
    {
        
        private string AVSResultField;
        
        private string AuthCodeField;
        
        private System.Nullable<decimal> AuthorizedAmountField;
        
        private string CVVResultField;
        
        private bool IsTransactionApprovedField;
        
        private string IssuerAuthenticationDataField;
        
        private string IssuerScriptTemplate1Field;
        
        private string IssuerScriptTemplate2Field;
        
        private string TokenField;
        
        private string TransactionIDField;
        
        private string TransactionMessageField;
        
        private System.Collections.Generic.KeyValuePair<string, string>[] TransactionOutputDetailsField;
        
        private string TransactionStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AVSResult
        {
            get
            {
                return this.AVSResultField;
            }
            set
            {
                this.AVSResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode
        {
            get
            {
                return this.AuthCodeField;
            }
            set
            {
                this.AuthCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AuthorizedAmount
        {
            get
            {
                return this.AuthorizedAmountField;
            }
            set
            {
                this.AuthorizedAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVVResult
        {
            get
            {
                return this.CVVResultField;
            }
            set
            {
                this.CVVResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTransactionApproved
        {
            get
            {
                return this.IsTransactionApprovedField;
            }
            set
            {
                this.IsTransactionApprovedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuerAuthenticationData
        {
            get
            {
                return this.IssuerAuthenticationDataField;
            }
            set
            {
                this.IssuerAuthenticationDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuerScriptTemplate1
        {
            get
            {
                return this.IssuerScriptTemplate1Field;
            }
            set
            {
                this.IssuerScriptTemplate1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuerScriptTemplate2
        {
            get
            {
                return this.IssuerScriptTemplate2Field;
            }
            set
            {
                this.IssuerScriptTemplate2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionMessage
        {
            get
            {
                return this.TransactionMessageField;
            }
            set
            {
                this.TransactionMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] TransactionOutputDetails
        {
            get
            {
                return this.TransactionOutputDetailsField;
            }
            set
            {
                this.TransactionOutputDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionStatus
        {
            get
            {
                return this.TransactionStatusField;
            }
            set
            {
                this.TransactionStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessEMVSREDRequest", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessEMVSREDRequest : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private Magensa.MPPGv3.ServiceClient.Authentication AuthenticationField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.EMVSREDInput EMVSREDInputField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.EMVSREDInput EMVSREDInput
        {
            get
            {
                return this.EMVSREDInputField;
            }
            set
            {
                this.EMVSREDInputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInput
        {
            get
            {
                return this.TransactionInputField;
            }
            set
            {
                this.TransactionInputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMVSREDInput", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class EMVSREDInput : object
    {
        
        private string EMVSREDDataField;
        
        private string EncryptionTypeField;
        
        private string KSNField;
        
        private int NumberOfPaddedBytesField;
        
        private Magensa.MPPGv3.ServiceClient.PaymentMode PaymentModeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EMVSREDData
        {
            get
            {
                return this.EMVSREDDataField;
            }
            set
            {
                this.EMVSREDDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EncryptionType
        {
            get
            {
                return this.EncryptionTypeField;
            }
            set
            {
                this.EncryptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumberOfPaddedBytes
        {
            get
            {
                return this.NumberOfPaddedBytesField;
            }
            set
            {
                this.NumberOfPaddedBytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.PaymentMode PaymentMode
        {
            get
            {
                return this.PaymentModeField;
            }
            set
            {
                this.PaymentModeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentMode", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public enum PaymentMode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MagStripe = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMV = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManualEntry = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessEMVSREDResponse", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessEMVSREDResponse : object
    {
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.EMVSREDOutput EMVSREDOutputField;
        
        private Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFaultField;
        
        private string MagTranIDField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutputField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.EMVSREDOutput EMVSREDOutput
        {
            get
            {
                return this.EMVSREDOutputField;
            }
            set
            {
                this.EMVSREDOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFault
        {
            get
            {
                return this.MPPGv3WSFaultField;
            }
            set
            {
                this.MPPGv3WSFaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutput
        {
            get
            {
                return this.TransactionOutputField;
            }
            set
            {
                this.TransactionOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMVSREDOutput", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class EMVSREDOutput : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputDataField;
        
        private string CardIDField;
        
        private System.Nullable<bool> IsReplayField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalOutputData
        {
            get
            {
                return this.AdditionalOutputDataField;
            }
            set
            {
                this.AdditionalOutputDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardID
        {
            get
            {
                return this.CardIDField;
            }
            set
            {
                this.CardIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsReplay
        {
            get
            {
                return this.IsReplayField;
            }
            set
            {
                this.IsReplayField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessReferenceIDRequest", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessReferenceIDRequest : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private Magensa.MPPGv3.ServiceClient.Authentication AuthenticationField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.ReferenceIDTransactionInput TransactionInputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.ReferenceIDTransactionInput TransactionInput
        {
            get
            {
                return this.TransactionInputField;
            }
            set
            {
                this.TransactionInputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessReferenceIDResponse", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessReferenceIDResponse : object
    {
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFaultField;
        
        private string MagTranIDField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutputField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFault
        {
            get
            {
                return this.MPPGv3WSFaultField;
            }
            set
            {
                this.MPPGv3WSFaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutput
        {
            get
            {
                return this.TransactionOutputField;
            }
            set
            {
                this.TransactionOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessManualEntryRequest", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessManualEntryRequest : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private Magensa.MPPGv3.ServiceClient.Authentication AuthenticationField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.ManualEntryInput ManualEntryInputField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.ManualEntryInput ManualEntryInput
        {
            get
            {
                return this.ManualEntryInputField;
            }
            set
            {
                this.ManualEntryInputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInput
        {
            get
            {
                return this.TransactionInputField;
            }
            set
            {
                this.TransactionInputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManualEntryInput", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ManualEntryInput : object
    {
        
        private string AddressLine1Field;
        
        private string AddressLine2Field;
        
        private string CVVField;
        
        private string CityField;
        
        private string CountryField;
        
        private string ExpirationDateField;
        
        private string NameOnCardField;
        
        private string PANField;
        
        private string StateField;
        
        private string ZIPField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1
        {
            get
            {
                return this.AddressLine1Field;
            }
            set
            {
                this.AddressLine1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2
        {
            get
            {
                return this.AddressLine2Field;
            }
            set
            {
                this.AddressLine2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVV
        {
            get
            {
                return this.CVVField;
            }
            set
            {
                this.CVVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameOnCard
        {
            get
            {
                return this.NameOnCardField;
            }
            set
            {
                this.NameOnCardField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PAN
        {
            get
            {
                return this.PANField;
            }
            set
            {
                this.PANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZIP
        {
            get
            {
                return this.ZIPField;
            }
            set
            {
                this.ZIPField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessManualEntryResponse", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessManualEntryResponse : object
    {
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFaultField;
        
        private string MagTranIDField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutputField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFault
        {
            get
            {
                return this.MPPGv3WSFaultField;
            }
            set
            {
                this.MPPGv3WSFaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutput
        {
            get
            {
                return this.TransactionOutputField;
            }
            set
            {
                this.TransactionOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessTokenRequest", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessTokenRequest : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private Magensa.MPPGv3.ServiceClient.Authentication AuthenticationField;
        
        private string CustomerTransactionIDField;
        
        private string TokenField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInput
        {
            get
            {
                return this.TransactionInputField;
            }
            set
            {
                this.TransactionInputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessTokenResponse", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessTokenResponse : object
    {
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFaultField;
        
        private string MagTranIDField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutputField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFault
        {
            get
            {
                return this.MPPGv3WSFaultField;
            }
            set
            {
                this.MPPGv3WSFaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutput
        {
            get
            {
                return this.TransactionOutputField;
            }
            set
            {
                this.TransactionOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessEncryptedManualEntryRequest", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessEncryptedManualEntryRequest : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private Magensa.MPPGv3.ServiceClient.Authentication AuthenticationField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.EncryptedManualEntryInput EncryptedManualEntryInputField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.EncryptedManualEntryInput EncryptedManualEntryInput
        {
            get
            {
                return this.EncryptedManualEntryInputField;
            }
            set
            {
                this.EncryptedManualEntryInputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInput
        {
            get
            {
                return this.TransactionInputField;
            }
            set
            {
                this.TransactionInputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncryptedManualEntryInput", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class EncryptedManualEntryInput : object
    {
        
        private string EncryptedDataField;
        
        private string KSNField;
        
        private Magensa.MPPGv3.ServiceClient.KeyVariant KeyVariantField;
        
        private int NumberOfPaddedBytesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EncryptedData
        {
            get
            {
                return this.EncryptedDataField;
            }
            set
            {
                this.EncryptedDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KSN
        {
            get
            {
                return this.KSNField;
            }
            set
            {
                this.KSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.KeyVariant KeyVariant
        {
            get
            {
                return this.KeyVariantField;
            }
            set
            {
                this.KeyVariantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumberOfPaddedBytes
        {
            get
            {
                return this.NumberOfPaddedBytesField;
            }
            set
            {
                this.NumberOfPaddedBytesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyVariant", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public enum KeyVariant : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Data = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessEncryptedManualEntryResponse", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessEncryptedManualEntryResponse : object
    {
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFaultField;
        
        private string MagTranIDField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutputField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFault
        {
            get
            {
                return this.MPPGv3WSFaultField;
            }
            set
            {
                this.MPPGv3WSFaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutput
        {
            get
            {
                return this.TransactionOutputField;
            }
            set
            {
                this.TransactionOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessKeyPadEntryRequest", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessKeyPadEntryRequest : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private Magensa.MPPGv3.ServiceClient.Authentication AuthenticationField;
        
        private Magensa.MPPGv3.ServiceClient.CardSwipeInput CardSwipeInputField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.CardSwipeInput CardSwipeInput
        {
            get
            {
                return this.CardSwipeInputField;
            }
            set
            {
                this.CardSwipeInputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInput
        {
            get
            {
                return this.TransactionInputField;
            }
            set
            {
                this.TransactionInputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessKeyPadEntryResponse", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class ProcessKeyPadEntryResponse : object
    {
        
        private Magensa.MPPGv3.ServiceClient.CardSwipeOutput CardSwipeOutputField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFaultField;
        
        private string MagTranIDField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutputField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.CardSwipeOutput CardSwipeOutput
        {
            get
            {
                return this.CardSwipeOutputField;
            }
            set
            {
                this.CardSwipeOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFault
        {
            get
            {
                return this.MPPGv3WSFaultField;
            }
            set
            {
                this.MPPGv3WSFaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutput
        {
            get
            {
                return this.TransactionOutputField;
            }
            set
            {
                this.TransactionOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProcessorReportRequest", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class GetProcessorReportRequest : object
    {
        
        private System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestDataField;
        
        private Magensa.MPPGv3.ServiceClient.Authentication AuthenticationField;
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] AdditionalRequestData
        {
            get
            {
                return this.AdditionalRequestDataField;
            }
            set
            {
                this.AdditionalRequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.Authentication Authentication
        {
            get
            {
                return this.AuthenticationField;
            }
            set
            {
                this.AuthenticationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Magensa.MPPGv3.ServiceClient.TransactionInput TransactionInput
        {
            get
            {
                return this.TransactionInputField;
            }
            set
            {
                this.TransactionInputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProcessorReportResponse", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
    public partial class GetProcessorReportResponse : object
    {
        
        private string CustomerTransactionIDField;
        
        private Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFaultField;
        
        private string MagTranIDField;
        
        private Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutputField;
        
        private string TransactionUTCTimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTransactionID
        {
            get
            {
                return this.CustomerTransactionIDField;
            }
            set
            {
                this.CustomerTransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.MPPGv3WSFault MPPGv3WSFault
        {
            get
            {
                return this.MPPGv3WSFaultField;
            }
            set
            {
                this.MPPGv3WSFaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MagTranID
        {
            get
            {
                return this.MagTranIDField;
            }
            set
            {
                this.MagTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Magensa.MPPGv3.ServiceClient.TransactionOutput TransactionOutput
        {
            get
            {
                return this.TransactionOutputField;
            }
            set
            {
                this.TransactionOutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionUTCTimestamp
        {
            get
            {
                return this.TransactionUTCTimestampField;
            }
            set
            {
                this.TransactionUTCTimestampField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.magensa.net/MPPGv3/", ConfigurationName="Magensa.MPPGv3.ServiceClient.IMPPGv3Service")]
    public interface IMPPGv3Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessCardSwipe", ReplyAction="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessCardSwipeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.MPPGv3.ServiceClient.MPPGv3WSFault), Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessCardSwipeMPPGv3WSFaultFault", Name="MPPGv3WSFault", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
        System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessCardSwipeResponse[]> ProcessCardSwipeAsync(Magensa.MPPGv3.ServiceClient.ProcessCardSwipeRequest[] ProcessCardSwipeRequests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessEMVSRED", ReplyAction="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessEMVSREDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.MPPGv3.ServiceClient.MPPGv3WSFault), Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessEMVSREDMPPGv3WSFaultFault", Name="MPPGv3WSFault", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
        System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessEMVSREDResponse[]> ProcessEMVSREDAsync(Magensa.MPPGv3.ServiceClient.ProcessEMVSREDRequest[] ProcessEMVSREDRequests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessReferenceID", ReplyAction="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessReferenceIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.MPPGv3.ServiceClient.MPPGv3WSFault), Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessReferenceIDMPPGv3WSFaultFault" +
            "", Name="MPPGv3WSFault", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
        System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessReferenceIDResponse[]> ProcessReferenceIDAsync(Magensa.MPPGv3.ServiceClient.ProcessReferenceIDRequest[] ProcessReferenceIDRequests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessManualEntry", ReplyAction="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessManualEntryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.MPPGv3.ServiceClient.MPPGv3WSFault), Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessManualEntryMPPGv3WSFaultFault" +
            "", Name="MPPGv3WSFault", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
        System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessManualEntryResponse[]> ProcessManualEntryAsync(Magensa.MPPGv3.ServiceClient.ProcessManualEntryRequest[] ProcessManualEntryRequests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessToken", ReplyAction="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessTokenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.MPPGv3.ServiceClient.MPPGv3WSFault), Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessTokenMPPGv3WSFaultFault", Name="MPPGv3WSFault", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
        System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessTokenResponse[]> ProcessTokenAsync(Magensa.MPPGv3.ServiceClient.ProcessTokenRequest[] ProcessTokenRequests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessEncryptedManualEntry", ReplyAction="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessEncryptedManualEntryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.MPPGv3.ServiceClient.MPPGv3WSFault), Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessEncryptedManualEntryMPPGv3WSF" +
            "aultFault", Name="MPPGv3WSFault", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
        System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessEncryptedManualEntryResponse[]> ProcessEncryptedManualEntryAsync(Magensa.MPPGv3.ServiceClient.ProcessEncryptedManualEntryRequest[] ProcessEncryptedManualEntryRequests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessKeyPadEntry", ReplyAction="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessKeyPadEntryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.MPPGv3.ServiceClient.MPPGv3WSFault), Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/ProcessKeyPadEntryMPPGv3WSFaultFault" +
            "", Name="MPPGv3WSFault", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
        System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessKeyPadEntryResponse[]> ProcessKeyPadEntryAsync(Magensa.MPPGv3.ServiceClient.ProcessKeyPadEntryRequest[] ProcessKeyPadEntryRequests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/GetProcessorReport", ReplyAction="http://www.magensa.net/MPPGv3/IMPPGv3Service/GetProcessorReportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magensa.MPPGv3.ServiceClient.MPPGv3WSFault), Action="http://www.magensa.net/MPPGv3/IMPPGv3Service/GetProcessorReportMPPGv3WSFaultFault" +
            "", Name="MPPGv3WSFault", Namespace="http://schemas.datacontract.org/2004/07/MPPGv3WS.Core")]
        System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.GetProcessorReportResponse[]> GetProcessorReportAsync(Magensa.MPPGv3.ServiceClient.GetProcessorReportRequest[] GetProcessorReportRequests);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IMPPGv3ServiceChannel : Magensa.MPPGv3.ServiceClient.IMPPGv3Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MPPGv3ServiceClient : System.ServiceModel.ClientBase<Magensa.MPPGv3.ServiceClient.IMPPGv3Service>, Magensa.MPPGv3.ServiceClient.IMPPGv3Service
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MPPGv3ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MPPGv3ServiceClient.GetBindingForEndpoint(endpointConfiguration), MPPGv3ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MPPGv3ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MPPGv3ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MPPGv3ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MPPGv3ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MPPGv3ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessCardSwipeResponse[]> ProcessCardSwipeAsync(Magensa.MPPGv3.ServiceClient.ProcessCardSwipeRequest[] ProcessCardSwipeRequests)
        {
            return base.Channel.ProcessCardSwipeAsync(ProcessCardSwipeRequests);
        }
        
        public System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessEMVSREDResponse[]> ProcessEMVSREDAsync(Magensa.MPPGv3.ServiceClient.ProcessEMVSREDRequest[] ProcessEMVSREDRequests)
        {
            return base.Channel.ProcessEMVSREDAsync(ProcessEMVSREDRequests);
        }
        
        public System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessReferenceIDResponse[]> ProcessReferenceIDAsync(Magensa.MPPGv3.ServiceClient.ProcessReferenceIDRequest[] ProcessReferenceIDRequests)
        {
            return base.Channel.ProcessReferenceIDAsync(ProcessReferenceIDRequests);
        }
        
        public System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessManualEntryResponse[]> ProcessManualEntryAsync(Magensa.MPPGv3.ServiceClient.ProcessManualEntryRequest[] ProcessManualEntryRequests)
        {
            return base.Channel.ProcessManualEntryAsync(ProcessManualEntryRequests);
        }
        
        public System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessTokenResponse[]> ProcessTokenAsync(Magensa.MPPGv3.ServiceClient.ProcessTokenRequest[] ProcessTokenRequests)
        {
            return base.Channel.ProcessTokenAsync(ProcessTokenRequests);
        }
        
        public System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessEncryptedManualEntryResponse[]> ProcessEncryptedManualEntryAsync(Magensa.MPPGv3.ServiceClient.ProcessEncryptedManualEntryRequest[] ProcessEncryptedManualEntryRequests)
        {
            return base.Channel.ProcessEncryptedManualEntryAsync(ProcessEncryptedManualEntryRequests);
        }
        
        public System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.ProcessKeyPadEntryResponse[]> ProcessKeyPadEntryAsync(Magensa.MPPGv3.ServiceClient.ProcessKeyPadEntryRequest[] ProcessKeyPadEntryRequests)
        {
            return base.Channel.ProcessKeyPadEntryAsync(ProcessKeyPadEntryRequests);
        }
        
        public System.Threading.Tasks.Task<Magensa.MPPGv3.ServiceClient.GetProcessorReportResponse[]> GetProcessorReportAsync(Magensa.MPPGv3.ServiceClient.GetProcessorReportRequest[] GetProcessorReportRequests)
        {
            return base.Channel.GetProcessorReportAsync(GetProcessorReportRequests);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMPPGv3Service))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IMPPGv3Service))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMPPGv3Service))
            {
                return new System.ServiceModel.EndpointAddress("http://mppg.magensa.net/V3/MPPGv3Service.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IMPPGv3Service))
            {
                return new System.ServiceModel.EndpointAddress("https://mppg.magensa.net/V3/MPPGv3Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMPPGv3Service,
            
            BasicHttpsBinding_IMPPGv3Service,
        }
    }
}
